#!/usr/bin/env bash
set -euo pipefail

./nemoage ini_files_burnin/sc_p05_dispersed_rep01_burnin.ini
./nemoage ini_files_run/sc_p05_dispersed_rep01.ini
./nemoage ini_files_burnin/sc_p05_dispersed_rep02_burnin.ini
./nemoage ini_files_run/sc_p05_dispersed_rep02.ini
./nemoage ini_files_burnin/sc_p05_dispersed_rep03_burnin.ini
./nemoage ini_files_run/sc_p05_dispersed_rep03.ini
./nemoage ini_files_burnin/sc_p05_dispersed_rep04_burnin.ini
./nemoage ini_files_run/sc_p05_dispersed_rep04.ini
./nemoage ini_files_burnin/sc_p05_dispersed_rep05_burnin.ini
./nemoage ini_files_run/sc_p05_dispersed_rep05.ini
./nemoage ini_files_burnin/sc_p05_small_clusters_rep01_burnin.ini
./nemoage ini_files_run/sc_p05_small_clusters_rep01.ini
./nemoage ini_files_burnin/sc_p05_small_clusters_rep02_burnin.ini
./nemoage ini_files_run/sc_p05_small_clusters_rep02.ini
./nemoage ini_files_burnin/sc_p05_small_clusters_rep03_burnin.ini
./nemoage ini_files_run/sc_p05_small_clusters_rep03.ini
./nemoage ini_files_burnin/sc_p05_small_clusters_rep04_burnin.ini
./nemoage ini_files_run/sc_p05_small_clusters_rep04.ini
./nemoage ini_files_burnin/sc_p05_small_clusters_rep05_burnin.ini
./nemoage ini_files_run/sc_p05_small_clusters_rep05.ini
./nemoage ini_files_burnin/sc_p05_big_clusters_rep01_burnin.ini
./nemoage ini_files_run/sc_p05_big_clusters_rep01.ini
./nemoage ini_files_burnin/sc_p05_big_clusters_rep02_burnin.ini
./nemoage ini_files_run/sc_p05_big_clusters_rep02.ini
./nemoage ini_files_burnin/sc_p05_big_clusters_rep03_burnin.ini
./nemoage ini_files_run/sc_p05_big_clusters_rep03.ini
./nemoage ini_files_burnin/sc_p05_big_clusters_rep04_burnin.ini
./nemoage ini_files_run/sc_p05_big_clusters_rep04.ini
./nemoage ini_files_burnin/sc_p05_big_clusters_rep05_burnin.ini
./nemoage ini_files_run/sc_p05_big_clusters_rep05.ini
./nemoage ini_files_burnin/sc_p20_dispersed_rep01_burnin.ini
./nemoage ini_files_run/sc_p20_dispersed_rep01.ini
./nemoage ini_files_burnin/sc_p20_dispersed_rep02_burnin.ini
./nemoage ini_files_run/sc_p20_dispersed_rep02.ini
./nemoage ini_files_burnin/sc_p20_dispersed_rep03_burnin.ini
./nemoage ini_files_run/sc_p20_dispersed_rep03.ini
./nemoage ini_files_burnin/sc_p20_dispersed_rep04_burnin.ini
./nemoage ini_files_run/sc_p20_dispersed_rep04.ini
./nemoage ini_files_burnin/sc_p20_dispersed_rep05_burnin.ini
./nemoage ini_files_run/sc_p20_dispersed_rep05.ini
./nemoage ini_files_burnin/sc_p20_small_clusters_rep01_burnin.ini
./nemoage ini_files_run/sc_p20_small_clusters_rep01.ini
./nemoage ini_files_burnin/sc_p20_small_clusters_rep02_burnin.ini
./nemoage ini_files_run/sc_p20_small_clusters_rep02.ini
./nemoage ini_files_burnin/sc_p20_small_clusters_rep03_burnin.ini
./nemoage ini_files_run/sc_p20_small_clusters_rep03.ini
./nemoage ini_files_burnin/sc_p20_small_clusters_rep04_burnin.ini
./nemoage ini_files_run/sc_p20_small_clusters_rep04.ini
./nemoage ini_files_burnin/sc_p20_small_clusters_rep05_burnin.ini
./nemoage ini_files_run/sc_p20_small_clusters_rep05.ini
./nemoage ini_files_burnin/sc_p20_big_clusters_rep01_burnin.ini
./nemoage ini_files_run/sc_p20_big_clusters_rep01.ini
./nemoage ini_files_burnin/sc_p20_big_clusters_rep02_burnin.ini
./nemoage ini_files_run/sc_p20_big_clusters_rep02.ini
./nemoage ini_files_burnin/sc_p20_big_clusters_rep03_burnin.ini
./nemoage ini_files_run/sc_p20_big_clusters_rep03.ini
./nemoage ini_files_burnin/sc_p20_big_clusters_rep04_burnin.ini
./nemoage ini_files_run/sc_p20_big_clusters_rep04.ini
./nemoage ini_files_burnin/sc_p20_big_clusters_rep05_burnin.ini
./nemoage ini_files_run/sc_p20_big_clusters_rep05.ini
./nemoage ini_files_burnin/sc_p50_dispersed_rep01_burnin.ini
./nemoage ini_files_run/sc_p50_dispersed_rep01.ini
./nemoage ini_files_burnin/sc_p50_dispersed_rep02_burnin.ini
./nemoage ini_files_run/sc_p50_dispersed_rep02.ini
./nemoage ini_files_burnin/sc_p50_dispersed_rep03_burnin.ini
./nemoage ini_files_run/sc_p50_dispersed_rep03.ini
./nemoage ini_files_burnin/sc_p50_dispersed_rep04_burnin.ini
./nemoage ini_files_run/sc_p50_dispersed_rep04.ini
./nemoage ini_files_burnin/sc_p50_dispersed_rep05_burnin.ini
./nemoage ini_files_run/sc_p50_dispersed_rep05.ini
./nemoage ini_files_burnin/sc_p50_small_clusters_rep01_burnin.ini
./nemoage ini_files_run/sc_p50_small_clusters_rep01.ini
./nemoage ini_files_burnin/sc_p50_small_clusters_rep02_burnin.ini
./nemoage ini_files_run/sc_p50_small_clusters_rep02.ini
./nemoage ini_files_burnin/sc_p50_small_clusters_rep03_burnin.ini
./nemoage ini_files_run/sc_p50_small_clusters_rep03.ini
./nemoage ini_files_burnin/sc_p50_small_clusters_rep04_burnin.ini
./nemoage ini_files_run/sc_p50_small_clusters_rep04.ini
./nemoage ini_files_burnin/sc_p50_small_clusters_rep05_burnin.ini
./nemoage ini_files_run/sc_p50_small_clusters_rep05.ini
./nemoage ini_files_burnin/sc_p50_big_clusters_rep01_burnin.ini
./nemoage ini_files_run/sc_p50_big_clusters_rep01.ini
./nemoage ini_files_burnin/sc_p50_big_clusters_rep02_burnin.ini
./nemoage ini_files_run/sc_p50_big_clusters_rep02.ini
./nemoage ini_files_burnin/sc_p50_big_clusters_rep03_burnin.ini
./nemoage ini_files_run/sc_p50_big_clusters_rep03.ini
./nemoage ini_files_burnin/sc_p50_big_clusters_rep04_burnin.ini
./nemoage ini_files_run/sc_p50_big_clusters_rep04.ini
./nemoage ini_files_burnin/sc_p50_big_clusters_rep05_burnin.ini
./nemoage ini_files_run/sc_p50_big_clusters_rep05.ini
